name: Actualizar Partidos Mundial
on:
  workflow_dispatch: # Esto habilita el botón manual para que lo oprimas desde tu cel
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta automáticamente cada 6 horas

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para poder guardar el JSON en el repo
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Ejecutar script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: node generarJson.js
      - name: Guardar cambios
        run: |
          git config user.name "Bot Mundial"
          git config user.email "bot@mundial.com"
          git add partidos.json
          git commit -m "Actualización automática de datos"
          git push